# image: node:lts
image: cypress/base:16.14.2
cache:
  # untracked: true
  key: cache_yarn
  paths:
    - .cache_yarn

stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - echo "Installing dependencies..."
    - yarn install --cache-folder ../.cache_yarn --frozen-lockfile
    
  only :
    - staging
    - prod
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  script:
    - yarn build:prod
  only :
    - staging
    - prod
  dependencies:
    - install
  artifacts:
    paths:
      - build

unit-test:
  stage: test
  script:
    - yarn test
  only :
    - staging
    - prod
  dependencies:
    - install

cypress-test:
  stage: test
  script:
    - yarn start &
    - npm install --save-dev cypress
    - yarn cypress install
    - yarn run cypress verify
    - yarn run cypress run --config baseUrl=http://localhost:3000
  only :
    - staging
    - prod
  dependencies:
    - install

deploy_prod:
  stage: deploy
  script:
    - echo "test"
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase use prod --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN
  only :
    - prod
  environment:
    name: prod
  dependencies:
    - install
    - build